// USER ACTIONS
export const USER_GET_DATA = "USER_GET_DATA";
export const USER_GET_DATA_SUCCESS = "USER_GET_DATA_SUCCESS";
export const USER_GET_DATA_REPOS = "USER_GET_DATA_REPOS";
export const USER_GET_DATA_REPOS_SUCCESS = "USER_GET_DATA_REPOS_SUCCESS";
export const USER_GET_DATA_STARRED = "USER_GET_DATA_STARRED";
export const USER_GET_DATA_STARRED_SUCCESS = "USER_GET_DATA_STARRED_SUCCESS";
export const USER_GET_DATA_FAIL = "USER_GET_DATA_FAIL";
export const USER_GET_DATA_REPOS_FAIL = "USER_GET_DATA_REPOS_FAIL";
export const USER_GET_DATA_STARRED_FAIL = "USER_GET_DATA_STARRED_FAIL";

//ALERT
export const TOGGLE_ALERT = "TOGGLE_ALERT";
